const TeamData = [
  {
    name: "Samson Chan",
    job: "Chairman | Co-Founder",
    image: "/Samson_Chan_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/samson-chan/",
    bgColor: "bg-purple-500",
  },
  {
    name: "Abdulmalik O. Iyiola",
    job: "Director | Co-Founder",
    image: "/Abdulmalik_Iyiola_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/abdulmalikiyiola/",
    bgColor: "bg-teal-500",
  },
  {
    name: "Nikhil Sharma",
    job: "Tech Lead",
    image: "/Nikhil_Sharma_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/nikhilsharma26500/",
    bgColor: "bg-purple-500",
  },
  {
    name: "Natalie Au",
    job: "Project Manager",
    image: "/Natalie_Au_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/natalliiieeee/",
    bgColor: "bg-orange-500",
  },
  {
    name: "Daniel Kim",
    job: "Software Developer",
    image: "/Daniel_Kim_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/danielw-kim/",
    bgColor: "bg-teal-500",
  },
  {
    name: "Seth",
    job: "Software Developer",
    image: "/Seth_Li_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/zhaohui-li-a75234263/",
    bgColor: "bg-orange-500",
  },
  {
    name: "Luana Madeira",
    job: "Software Developer",
    image: "/Luana_Madeira_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/luanamadeira/",
    bgColor: "bg-purple-500",
  },
  {
    name: "Gloria Boakye Yiadom",
    job: "Social Media Manager",
    image: "/Gloria_Boakye_Yiadom_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/gloria-boakye-yiadom-300b9721b/",
    bgColor: "bg-purple-500",
  },
  {
    name: "Zakiya Tasneem",
    job: "Social Media Manager",
    image: "/Zakiya_Tasneem_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/tasneemzakiya/",
    bgColor: "bg-purple-500",
  },
  {
    name: "Huyen Le",
    job: "Student Ambassador",
    image: "/Huyen_Le_pic.jpeg",
    linkedin: "https://www.linkedin.com/in/huyenttle/",
    bgColor: "bg-purple-500",
  },
];
export default TeamData;
